version: '3.2'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y git &&
      curl -fsSL https://get.docker.com -o get-docker.sh &&
      sh get-docker.sh &&
      rm get-docker.sh &&
      /usr/local/bin/jenkins.sh
      "

volumes:
  jenkins_home: