pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Utiliser checkout scm qui fonctionne mieux avec Jenkins
                checkout scm
            }
        }
        stage('Install') {
            steps {
                dir('app') {
                    sh 'npm install'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Construire l'image Docker depuis le dossier app
                    sh 'docker build -t jenkinslab:latest ./app'
                }
            }
        }
        stage('Run Tests') {
            steps {
                dir('app') {
                    sh 'npm test'
                }
            }
        }

    }

    post {
        always {
            // Nettoyer les images Docker pour éviter l'accumulation
            sh 'docker system prune -f || true'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
