pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/anthonystln/JenkinsLab.git'
            }
        }
        stage('Install') {
            steps {
                dir('app') {
                    sh 'npm install'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t jenkinslab:latest ./app'
                }
            }
        }
    }
}
